### ISSUE TITLE
Update Perl 6 to 2017.01

### ISSUE THREAD

**Issue by MasterDuke17** [prasmussen/glot-containers#18]
I'm not sure which you use, but both a Rakudo compiler (https://github.com/rakudo/rakudo/blob/nom/docs/announce/2017.01.md) and Rakudo Star (http://rakudo.org/2017/01/30/announce-rakudo-star-release-2017-01/) were just released.

**Comment by MattOates** [comment]
The container is set to be "latest" which is in theory 2017.01 right now https://hub.docker.com/_/rakudo-star/ I believe this is more about glot.io deployment than any code changes necessary.

**Comment by zoffixznet** [comment]
Looks to be up to date now: https://glot.io/snippets/eoepfrmsvt

**Comment by MasterDuke17** [comment]
Cool, closing the issue then.

**Comment by prasmussen** [comment]
All images have been updated and the perl6 version is now v2017.01
