### ISSUE TITLE
run push_images.sh file

### ISSUE THREAD

**Issue by ClearSeve** [prasmussen/glot-containers#21]
I have a problem, in the docker repository, I went to the sebgod user to view, did not find mercury-stable
Error from push_images.sh file
The error is as follows:
```
Status: Image is up to date for jimho/lua:latest
Error response from daemon: pull access denied for sebgod/mercury-stable, repository does not exist or may require 'docker login'
```

**Comment by ebramanti** [comment]
Related to this issue, the version of TypeScript being used is very out-of-date. I'm getting errors for missing ES6 features such as `Set`.

Edit: Looks like it's been 9 months since [the TypeScript container](https://hub.docker.com/r/glot/typescript) was updated.

**Comment by prasmussen** [comment]
> I have a problem, in the docker repository, I went to the sebgod user to view, did not find mercury-stable
> Error from push_images.sh file
> The error is as follows:
> 
> ```
> Status: Image is up to date for jimho/lua:latest
> Error response from daemon: pull access denied for sebgod/mercury-stable, repository does not exist or may require 'docker login'
> ```

`sebgod/mercury-stable` does not seem to exist any more so I have changed the Dockerfile to use `sebgod/mercury`

**Comment by prasmussen** [comment]
> Related to this issue, the version of TypeScript being used is very out-of-date. I'm getting errors for missing ES6 features such as `Set`.
> 
> Edit: Looks like it's been 9 months since [the TypeScript container](https://hub.docker.com/r/glot/typescript) was updated.

TypeScript is now updated to 3.9.3
