### ISSUE TITLE
Mono Container doesn't read stdin

### ISSUE THREAD

**Issue by kmahmassani** [prasmussen/glot-containers#24]
When sending 
`{"language":"csharp","files":[{"name":"main.cs","content":"using System;\n\nclass MainClass {\n    static void Main(string[] args) {\n        Console.WriteLine(\"Hello \" + args[0] + \"!\");\n    }\n}","stdin":"World"}]}`
to glot/mono the following output is returned:
`{"stdout":"","stderr":"\nUnhandled Exception:\nSystem.IndexOutOfRangeException: Index was outside the bounds of the array.\n  at MainClass.Main (System.String[] args) [0x00000] in \u003ccda5bdbe52cf40e7b24ea0bace4591a2\u003e:0 \n[ERROR] FATAL UNHANDLED EXCEPTION: System.IndexOutOfRangeException: Index was outside the bounds of the array.\n  at MainClass.Main (System.String[] args) [0x00000] in \u003ccda5bdbe52cf40e7b24ea0bace4591a2\u003e:0 \n","error":"exit status 1"}`

**Comment by prasmussen** [comment]
It looks like you are trying to read program arguments, not from stdin.
A google search  for `c# read from stdin` seems to give relevant results.

**Comment by kmahmassani** [comment]
My mistake sorry.  Although I am still having issues:

`{"language":"csharp","files":[{"name":"main.cs","content":"using System;\n\nclass MainClass {\n    static void Main() {\n        Console.WriteLine(\"Hello \" + Console.Read() + \"!\");\n    }\n}","stdin":"World"}]}`

returns:

`OUTPUT {"stdout":"Hello -1!\n","stderr":"","error":""}`

-1 stands for no character to read, so it's not able to read the text for some reason.  Any idea?

**Comment by prasmussen** [comment]
I'm not that familiar with c#, but `Console.ReadLine()` works on glot.io (which uses glot-containers): https://glot.io/snippets/fmepealj2z

**Comment by kmahmassani** [comment]
For anyone coming across this with the same issue, the problem was I had the `stdin` property inside of the `files` property and not in the root json object. Thank you @prasmussen for trying to help.
