### ISSUE TITLE
Node.js reports old version 0.12.7

### ISSUE THREAD

**Issue by styfle** [prasmussen/glot-containers#3]
See this snippet: https://glot.io/snippets/ee0aofby8o

``` js
console.log(process.version); // v0.12.7
```

Is this because the `node:latest` container needs to be rebuilt?
If this is not possible could you add the `node:argon` [LTS container](https://hub.docker.com/_/node/)?

**Comment by JimFung** [comment]
I just built `node:latest` for my own node project and its returning v5.10.1.

**Comment by prasmussen** [comment]
Container is rebuilt and node version is now v5.10.1
